name: Feature request
description: Suggest an idea for NetScreen
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would it be useful?
